### ISSUE TITLE
What exactly do species-background data refer to?

### ISSUE THREAD

**Issue by turningpoint1988** [seqcode/cross-species-domain-adaptation#3]
Are they binding peaks derived from the 'Human' and 'Mouse' species? Thanks a lot.

**Comment by kellycochran** [comment]
Hello,

The "species-background data" is randomly-sampled windows (not peaks) from either the human or mouse genomes (training chromosomes only). We don't consider binding information at all when sampling these windows because that would require having labels in the target species during training.

Hope this helps!

**Comment by turningpoint1988** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您所发的邮件已收到，我会尽快给您回复。
